// Generated by scripts/import-ebird.mjs. Edit data/aviary-curation.json, not this file.

export type Bird = { name: string; scientific: string; encounters: number; first: string; latest: string; regions: string[]; blurb: string };
export type Journey = { name: string; count: number; tone: string; x: number; y: number };
export type YearlySpecies = { year: number; species: number };

export const birds: Bird[] = [
  {
    "name": "Eurasian Tree Sparrow",
    "scientific": "Passer montanus",
    "encounters": 8,
    "first": "2026-06-20",
    "latest": "2026-07-02",
    "regions": [
      "Guangdong",
      "Hong Kong",
      "Yunnan"
    ],
    "blurb": "A rufous-capped sparrow with a black cheek spot, often moving in noisy flocks."
  },
  {
    "name": "American Robin",
    "scientific": "Turdus migratorius",
    "encounters": 4,
    "first": "2026-04-15",
    "latest": "2026-05-22",
    "regions": [
      "California"
    ],
    "blurb": "A gray-brown thrush with a warm orange belly that runs and pauses across lawns."
  },
  {
    "name": "House Finch",
    "scientific": "Haemorhous mexicanus",
    "encounters": 4,
    "first": "2026-04-16",
    "latest": "2026-05-22",
    "regions": [
      "California"
    ],
    "blurb": "A social, streaky finch; males wear rosy color around the face and breast."
  },
  {
    "name": "Blyth's Leaf Warbler",
    "scientific": "Phylloscopus reguloides",
    "encounters": 3,
    "first": "2026-06-25",
    "latest": "2026-06-25",
    "regions": [
      "Yunnan"
    ],
    "blurb": "A yellow-green forest warbler with a pale crown stripe and alternating wing flicks."
  },
  {
    "name": "Dark-eyed Junco",
    "scientific": "Junco hyemalis",
    "encounters": 3,
    "first": "2026-05-13",
    "latest": "2026-05-27",
    "regions": [
      "California"
    ],
    "blurb": "A ground-feeding sparrow with a pale bill and white outer tail feathers."
  },
  {
    "name": "White-crowned Sparrow",
    "scientific": "Zonotrichia leucophrys",
    "encounters": 3,
    "first": "2026-05-03",
    "latest": "2026-05-27",
    "regions": [
      "California"
    ],
    "blurb": "Bold black-and-white head stripes and a sweet whistled opening make it distinctive."
  },
  {
    "name": "Anna's Hummingbird",
    "scientific": "Calypte anna",
    "encounters": 2,
    "first": "2026-05-03",
    "latest": "2026-08-18",
    "regions": [
      "California"
    ],
    "blurb": "A green-and-gray hummingbird; males flash an iridescent rose-pink crown and throat."
  },
  {
    "name": "Red-whiskered Bulbul",
    "scientific": "Pycnonotus jocosus",
    "encounters": 2,
    "first": "2026-06-25",
    "latest": "2026-06-25",
    "regions": [
      "Yunnan"
    ],
    "blurb": "A tall-crested songbird with red cheek and undertail patches, often seen in pairs."
  },
  {
    "name": "Ring-billed Gull",
    "scientific": "Larus delawarensis",
    "encounters": 2,
    "first": "2026-04-12",
    "latest": "2026-04-12",
    "regions": [
      "New York",
      "Ontario"
    ],
    "blurb": "A sociable, medium-sized gull named for the black band around its yellow bill."
  },
  {
    "name": "Song Sparrow",
    "scientific": "Melospiza melodia",
    "encounters": 2,
    "first": "2024-03-27",
    "latest": "2026-05-03",
    "regions": [
      "California"
    ],
    "blurb": "A heavily streaked sparrow of brushy edges, with songs that vary across its range."
  },
  {
    "name": "Allen's Hummingbird",
    "scientific": "Selasphorus sasin",
    "encounters": 1,
    "first": "2026-05-03",
    "latest": "2026-05-03",
    "regions": [
      "California"
    ],
    "blurb": "A compact coppery-and-green hummingbird of coastal scrub, with narrow outer tail feathers."
  },
  {
    "name": "Barn Swallow",
    "scientific": "Hirundo rustica",
    "encounters": 1,
    "first": "2026-06-20",
    "latest": "2026-06-20",
    "regions": [
      "Guangdong"
    ],
    "blurb": "A blue-backed aerial hunter with an orange throat and a deeply forked tail."
  },
  {
    "name": "Bewick's Wren",
    "scientific": "Thryomanes bewickii",
    "encounters": 1,
    "first": "2026-05-13",
    "latest": "2026-05-13",
    "regions": [
      "California"
    ],
    "blurb": "A lively brown wren with a bold white eyebrow and a long, often upright tail."
  },
  {
    "name": "Black Phoebe",
    "scientific": "Sayornis nigricans",
    "encounters": 1,
    "first": "2026-05-22",
    "latest": "2026-05-22",
    "regions": [
      "California"
    ],
    "blurb": "A sooty flycatcher with a white belly that pumps its tail from low waterside perches."
  },
  {
    "name": "Black-capped Chickadee",
    "scientific": "Poecile atricapillus",
    "encounters": 1,
    "first": "2026-04-12",
    "latest": "2026-04-12",
    "regions": [
      "New York"
    ],
    "blurb": "A tiny acrobat with a black cap and bib, white cheeks, and familiar chick-a-dee calls."
  },
  {
    "name": "House Sparrow",
    "scientific": "Passer domesticus",
    "encounters": 1,
    "first": "2026-04-13",
    "latest": "2026-04-13",
    "regions": [
      "Ontario"
    ],
    "blurb": "A chunky, stout-billed sparrow closely tied to buildings, streets, and human activity."
  },
  {
    "name": "Lesser Goldfinch",
    "scientific": "Spinus psaltria",
    "encounters": 1,
    "first": "2026-05-03",
    "latest": "2026-05-03",
    "regions": [
      "California"
    ],
    "blurb": "A tiny seed-eating finch; males are yellow with a black cap and white wing patch."
  },
  {
    "name": "Little Grebe",
    "scientific": "Tachybaptus ruficollis",
    "encounters": 1,
    "first": "2026-06-24",
    "latest": "2026-06-24",
    "regions": [
      "Yunnan"
    ],
    "blurb": "A compact diving bird of reed-edged wetlands, with rusty neck sides in breeding plumage."
  },
  {
    "name": "Orange-crowned Warbler",
    "scientific": "Leiothlypis celata",
    "encounters": 1,
    "first": "2026-04-15",
    "latest": "2026-04-15",
    "regions": [
      "California"
    ],
    "blurb": "A plain olive warbler whose namesake orange crown is usually hidden from view."
  },
  {
    "name": "Pacific Wren",
    "scientific": "Troglodytes pacificus",
    "encounters": 1,
    "first": "2026-05-13",
    "latest": "2026-05-13",
    "regions": [
      "California"
    ],
    "blurb": "A tiny barred-brown wren that moves mouse-like through mossy forest understory."
  },
  {
    "name": "Purple Finch",
    "scientific": "Haemorhous purpureus",
    "encounters": 1,
    "first": "2024-03-27",
    "latest": "2024-03-27",
    "regions": [
      "California"
    ],
    "blurb": "A chunky forest finch; males carry a raspberry wash across the head and breast."
  },
  {
    "name": "Red-masked Parakeet",
    "scientific": "Psittacara erythrogenys",
    "encounters": 1,
    "first": "2024-03-27",
    "latest": "2024-03-27",
    "regions": [
      "California"
    ],
    "blurb": "A long-tailed green parakeet with a red face, usually announced by loud screeches."
  },
  {
    "name": "Red-shouldered Hawk",
    "scientific": "Buteo lineatus",
    "encounters": 1,
    "first": "2026-04-15",
    "latest": "2026-04-15",
    "regions": [
      "California"
    ],
    "blurb": "A richly barred woodland hawk with checkered wings and a rising, whistled call."
  },
  {
    "name": "Spotted Towhee",
    "scientific": "Pipilo maculatus",
    "encounters": 1,
    "first": "2026-05-13",
    "latest": "2026-05-13",
    "regions": [
      "California"
    ],
    "blurb": "A black, white, and rufous sparrow that scratches noisily through leaf litter."
  },
  {
    "name": "Steller's Jay",
    "scientific": "Cyanocitta stelleri",
    "encounters": 1,
    "first": "2026-04-22",
    "latest": "2026-04-22",
    "regions": [
      "California"
    ],
    "blurb": "A dark-crested blue jay of evergreen forests, known for bold curiosity and varied calls."
  },
  {
    "name": "Swinhoe's White-eye",
    "scientific": "Zosterops simplex",
    "encounters": 1,
    "first": "2026-06-20",
    "latest": "2026-06-20",
    "regions": [
      "Guangdong"
    ],
    "blurb": "A small olive-yellow bird with a bright white eyering, active from understory to canopy."
  },
  {
    "name": "Western Bluebird",
    "scientific": "Sialia mexicana",
    "encounters": 1,
    "first": "2026-08-18",
    "latest": "2026-08-18",
    "regions": [
      "California"
    ],
    "blurb": "A blue-and-rust thrush that drops from low perches to catch insects on the ground."
  },
  {
    "name": "Wilson's Warbler",
    "scientific": "Cardellina pusilla",
    "encounters": 1,
    "first": "2026-04-15",
    "latest": "2026-04-15",
    "regions": [
      "California"
    ],
    "blurb": "A bright yellow, restless warbler; males wear a small black cap."
  }
];

export const journeys: Journey[] = [
  {
    "name": "California",
    "count": 31,
    "tone": "clay",
    "x": 19.1,
    "y": 27.1
  },
  {
    "name": "Ontario",
    "count": 2,
    "tone": "sage",
    "x": 29.5,
    "y": 19.1
  },
  {
    "name": "New York",
    "count": 2,
    "tone": "blue",
    "x": 31.1,
    "y": 23.4
  },
  {
    "name": "Yunnan",
    "count": 10,
    "tone": "moss",
    "x": 77.3,
    "y": 34.5
  },
  {
    "name": "Guangdong",
    "count": 5,
    "tone": "gold",
    "x": 80.7,
    "y": 35.7
  },
  {
    "name": "Hong Kong",
    "count": 1,
    "tone": "rose",
    "x": 81,
    "y": 36.2
  }
];

export const yearlyNewSpecies: YearlySpecies[] = [
  {
    "year": 2024,
    "species": 3
  },
  {
    "year": 2025,
    "species": 0
  },
  {
    "year": 2026,
    "species": 25
  }
];

export const aviaryStats = {
  "species": 28,
  "encounters": 51,
  "regions": 6,
  "firstDate": "2024-03-27",
  "latestDate": "2026-08-18"
};
